/src/constants/cocMappings/troops.js
export const TROOP_NAME_ALIASES = {
    barbarian: "barbarian",
    archer: "archer",
    giant: "giant",
    goblin: "goblin",
    wallbreaker: "wallBreaker",
    balloon: "balloon",
    wizard: "wizard",
    healer: "healer",
    dragon: "dragon",
    pekka: "pekka",
    babydragon: "babyDragon",
    miner: "miner",
    electrodragon: "electroDragon",
    yeti: "yeti",
    dragonrider: "dragonRider",
    electrotitan: "electroTitan",
    rootrider: "rootRider",
    thrower: "thrower",
  
    minion: "minion",
    hogrider: "hogRider",
    valkyrie: "valkyrie",
    golem: "golem",
    witch: "witch",
    lavahound: "lavaHound",
    bowler: "bowler",
    icegolem: "iceGolem",
    headhunter: "headhunter",
    apprenticewarden: "apprenticeWarden"
  };